version: '3'

services:
  nginx:
    image: nginx:1.23.3
    ports:
      - 4444:4444
    volumes:
      - type: bind
        source: ./nginx/nginxconfig.io
        target: /etc/nginx/nginxconfig.io
      - type: bind
        source: ./nginx/sites-available/alertmoon.com.conf
        target: /etc/nginx/sites-available/alertmoon.com.conf
      - type: bind
        source: ./nginx/sites-available/alertmoon.com.conf
        target: /etc/nginx/sites-enabled/alertmoon.com.conf
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      # - ./ssl:/ssl/
    networks:
      - intranet

networks:
  intranet:
