name: Build docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show default environment variables
        run: |
          echo "NODE_ENV=${{ vars.NODE_ENV }}"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Build the Docker image
        run: docker build . --build-arg NODE_ENV=${{ vars.NODE_ENV }} --tag ${{ secrets.DOCKERHUB_USERNAME }}/alertmoon-backend:${{ steps.package-version.outputs.current-version}}

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/alertmoon-backend:${{ steps.package-version.outputs.current-version}}

      - name: Build the Docker image (latest)
        run: docker build . --build-arg NODE_ENV=${{ vars.NODE_ENV }} --tag ${{ secrets.DOCKERHUB_USERNAME }}/alertmoon-backend:latest

      - name: Push the Docker image (latest)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/alertmoon-backend:latest
