name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --tag metastasis/alertmoon-backend:$(date +%s)
      - name: Push the Docker image
        run: docker push -u metastasis
