name: Deploy docker image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.BACKEND_HOST }}
        username: ${{ secrets.BACKEND_USERNAME }}
        key: ${{ secrets.BACKEND_SSH_KEY }}
        script: |
          docker stop alertmoon_backend || true
          docker rm -fv alertmoon_backend || true
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/alertmoon-backend:latest
          docker run -d -i --name alertmoon_backend -p 3001:3001 \
            -e "ORY_SDK_URL=${{ secrets.ORY_SDK_URL }}" \
            -e "ORY_SDK_KETO_READ_URL=${{ secrets.ORY_SDK_KETO_READ_URL }}" \
            -e "ORY_SDK_KETO_WRITE_URL=${{ secrets.ORY_SDK_KETO_WRITE_URL }}" \
            -e "ORY_KETO_TOKEN=${{ secrets.ORY_KETO_TOKEN }}" \
            -e "ALERTMOON_MONGO_URL=${{ secrets.ALERTMOON_MONGO_URL }}" \
            -e "ALERTMOON_USE_HTTPS=false" \
            metastasis/alertmoon-backend:latest
